name = "PanelDataTools"
uuid = "f8e8dcbf-c8af-4c89-b3d0-30e7f728b8cf"
authors = ["Eirik Eylands Brandsaas"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
